import { useState } from "react";
import toast from "react-hot-toast";
import axiosInstance from "../api/axios";

export default function PrescriptionModal({
  checkup,
  patient,
  onClose,
  onSaved,
}) {
  const [pdfBase64, setPdfBase64] = useState(null);
  const [pdfUrl, setPdfUrl] = useState(checkup.prescription?.pdfUrl || null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isSending, setIsSending] = useState(false);

  const handleSendWhatsApp = async () => {
    setIsSending(true);
    try {
      await axiosInstance.post(`/prescriptions/send-whatsapp/${checkup._id}`);
      toast.success(`Prescription sent to ${patient.name} via WhatsApp! 📲`);
    } catch {
      toast.error("Failed to send via WhatsApp");
    } finally {
      setIsSending(false);
    }
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      // Generate PDF
      const res = await axiosInstance.post(
        `/prescriptions/generate/${checkup._id}`,
      );
      const base64 = res.data.pdf;
      setPdfBase64(base64);

      // Open in new tab for preview
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
      const blob = new Blob([bytes], { type: "application/pdf" });
      const blobUrl = URL.createObjectURL(blob);
      window.open(blobUrl, "_blank");

      // Auto save to Cloudinary
      const saveRes = await axiosInstance.post(
        `/prescriptions/save/${checkup._id}`,
      );
      const url = saveRes.data.pdfUrl;
      setPdfUrl(url);
      if (onSaved) onSaved(url);
      toast.success("Prescription saved!");
    } catch {
      toast.error("Failed to generate prescription");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveAndSend = async () => {
    setIsSaving(true);
    try {
      const res = await axiosInstance.post(
        `/prescriptions/save/${checkup._id}`,
      );
      const url = res.data.pdfUrl;
      setPdfUrl(url);
      if (onSaved) onSaved(url);
      toast.success("Prescription saved!");

      const phone = patient.phone.replace(/\D/g, "");
      const formattedPhone = phone.startsWith("0")
        ? "92" + phone.slice(1)
        : phone;
      const message = encodeURIComponent(
        `Dear ${patient.name}, your prescription from ${checkup.prescription?.diagnosis ? "for " + checkup.prescription.diagnosis : ""} is ready.\n\nDownload here: ${url}\n\nGenerated by MediMate.`,
      );
      window.open(`https://wa.me/${formattedPhone}?text=${message}`, "_blank");
    } catch {
      toast.error("Failed to save prescription");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDownload = () => {
    if (pdfBase64) {
      const link = document.createElement("a");
      link.href = `data:application/pdf;base64,${pdfBase64}`;
      link.download = `prescription_${patient.name}_${new Date().toISOString().split("T")[0]}.pdf`;
      link.click();
    } else if (pdfUrl) {
      window.open(pdfUrl, "_blank");
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex flex-col"
      style={{ background: "rgba(0,0,0,0.85)", backdropFilter: "blur(6px)" }}
    >
      {/* Top Bar */}
      <div
        className="flex items-center justify-between px-4 sm:px-6 py-3 flex-shrink-0"
        style={{
          background: "#0a1628",
          borderBottom: "1px solid rgba(16,184,169,0.2)",
        }}
      >
        <div className="flex items-center gap-3">
          <div
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "rgba(16,184,169,0.1)" }}
          >
            📋
          </div>
          <div>
            <p className="text-sm font-bold text-white">Prescription</p>
            <p className="text-xs" style={{ color: "#64748b" }}>
              {patient.name} · {checkup.prescription?.diagnosis}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Download */}
          {(pdfBase64 || pdfUrl) && (
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all hover:opacity-80"
              style={{ background: "rgba(255,255,255,0.07)", color: "white" }}
            >
              ⬇ Download
            </button>
          )}

          {/* Save & Send WhatsApp */}
          {pdfBase64 && !pdfUrl && (
            <button
              onClick={handleSaveAndSend}
              disabled={isSaving}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all hover:opacity-80 disabled:opacity-50"
              style={{ background: "#25D366", color: "white" }}
            >
              {isSaving ? "Saving..." : "📤 Save & Send WhatsApp"}
            </button>
          )}

          {/* Already saved — resend */}
          {pdfUrl && (
            <button
              onClick={handleSendWhatsApp}
              disabled={isSending}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all hover:opacity-80 disabled:opacity-50"
              style={{ background: "#25D366", color: "white" }}
            >
              {isSending ? "Sending..." : "📲 Send via WhatsApp"}
            </button>
          )}

          {/* Close */}
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg flex items-center justify-center transition-all hover:bg-white hover:bg-opacity-10"
            style={{ color: "#64748b" }}
          >
            ✕
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex items-center justify-center p-4 overflow-hidden">
        {/* Initial state */}
        {!pdfBase64 && !pdfUrl && (
          <div className="text-center">
            <div
              className="w-20 h-20 rounded-2xl flex items-center justify-center text-4xl mx-auto mb-4"
              style={{
                background: "rgba(16,184,169,0.1)",
                border: "1px solid rgba(16,184,169,0.2)",
              }}
            >
              📋
            </div>
            <h3 className="text-lg font-bold text-white mb-2">
              Generate Prescription
            </h3>
            <p className="text-sm mb-6" style={{ color: "#64748b" }}>
              Create a professional PDF prescription for {patient.name}
            </p>
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="px-6 py-3 rounded-xl text-sm font-bold text-white transition-all hover:scale-105 hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              style={{
                background: "linear-gradient(135deg,#10B8A9,#0d9488)",
                boxShadow: "0 4px 20px rgba(16,184,169,0.3)",
              }}
            >
              {isGenerating ? (
                <span className="flex items-center gap-2">
                  <span
                    className="w-4 h-4 rounded-full border-2 animate-spin inline-block"
                    style={{
                      borderColor: "white",
                      borderTopColor: "transparent",
                    }}
                  />
                  Generating...
                </span>
              ) : (
                "Generate PDF"
              )}
            </button>
          </div>
        )}

        {/* PDF Generated — preview opened in new tab */}
        {pdfBase64 && !pdfUrl && (
          <div className="text-center">
            <div
              className="w-20 h-20 rounded-2xl flex items-center justify-center text-4xl mx-auto mb-4"
              style={{
                background: "rgba(16,184,169,0.1)",
                border: "1px solid rgba(16,184,169,0.2)",
              }}
            >
              ✅
            </div>
            <h3 className="text-lg font-bold text-white mb-2">
              PDF Generated!
            </h3>
            <p className="text-sm mb-4" style={{ color: "#64748b" }}>
              Prescription opened in a new tab for preview.
            </p>
            <button
              onClick={handleGenerate}
              className="text-xs px-3 py-2 rounded-xl transition-all hover:opacity-80"
              style={{ background: "rgba(255,255,255,0.07)", color: "#94a3b8" }}
            >
              🔄 Regenerate
            </button>
          </div>
        )}

        {/* Already saved */}
        {pdfUrl && (
          <div
            className="w-full flex flex-col"
            style={{
              maxWidth: "900px",
              width: "100%",
              height: "calc(100vh - 150px)",
            }}
          >
            <iframe
              src={pdfUrl}
              className="w-full h-full rounded-2xl shadow-2xl"
              style={{ border: "none" }}
              title="Prescription Preview"
            />
          </div>
        )}
      </div>
    </div>
  );
}
