import pkg from "whatsapp-web.js";
const { Client, LocalAuth, MessageMedia } = pkg;
import qrcode from "qrcode-terminal";

let isClientReady = false;
let initInProgress = false;

const client = new Client({
  authStrategy: new LocalAuth(),
  puppeteer: {
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  },
});

client.on("qr", (qr) => {
  console.log("📱 Scan this QR code with WhatsApp Business:");
  qrcode.generate(qr, { small: true });
});

client.on("ready", () => {
  isClientReady = true;
  initInProgress = false;
  console.log("✅ WhatsApp MedAlerto is ready!");
});

client.on("auth_failure", (msg) => {
  isClientReady = false;
  initInProgress = false;
  console.error("❌ WhatsApp auth failed:", msg);
});

client.on("disconnected", (reason) => {
  isClientReady = false;
  console.log("❌ WhatsApp disconnected:", reason);
  // Only auto-reconnect if the disconnect was unexpected
  if (reason !== "LOGOUT") {
    setTimeout(() => {
      console.log("Attempting WhatsApp reconnection...");
      initializeWhatsApp().catch((err) =>
        console.error("Reconnect failed:", err.message),
      );
    }, 5000);
  }
});

const initializeWhatsApp = async () => {
  if (isClientReady || initInProgress) return;
  initInProgress = true;
  try {
    await client.initialize();
  } catch (error) {
    initInProgress = false;
    throw error;
  }
};

const normalizePakPhone = (phone) => {
  const digits = String(phone || "").replace(/\D/g, "");
  if (!digits) return null;

  if (digits.startsWith("92") && digits.length === 12) return digits;
  if (digits.startsWith("0092") && digits.length === 14) return digits.slice(2);
  if (digits.startsWith("0") && digits.length === 11) return `92${digits.slice(1)}`;
  if (digits.length === 10) return `92${digits}`;

  return digits;
};

const buildChatIdFromPhone = (phone) => {
  const normalized = normalizePakPhone(phone);
  if (!normalized || normalized.length < 11) {
    throw new Error("Invalid patient phone number for WhatsApp");
  }
  return `${normalized}@c.us`;
};

export const ensureWhatsAppReady = async (timeoutMs = 30000) => {
  if (isClientReady) return;

  await initializeWhatsApp();

  const startedAt = Date.now();
  while (!isClientReady) {
    if (Date.now() - startedAt > timeoutMs) {
      throw new Error(
        "WhatsApp client is not ready. Scan QR and wait for ready state.",
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
};

export const sendTextWhatsApp = async (phone, message) => {
  await ensureWhatsAppReady();
  const chatId = buildChatIdFromPhone(phone);

  const isRegistered = await client.isRegisteredUser(chatId);
  if (!isRegistered) {
    throw new Error(`Recipient is not a registered WhatsApp user: ${chatId}`);
  }

  await client.sendMessage(chatId, message);
};

initializeWhatsApp().catch((error) => {
  console.error("Failed to initialize WhatsApp client:", error.message);
});

export const sendPrescriptionWhatsApp = async (phone, patientName, doctorName, facilityName, facilityType, pdfBuffer) => {
  try {
    await ensureWhatsAppReady();
    const chatId = buildChatIdFromPhone(phone);

    const isRegistered = await client.isRegisteredUser(chatId);
    if (!isRegistered) {
      throw new Error(`Recipient is not a registered WhatsApp user: ${chatId}`);
    }

    const media = new MessageMedia(
      "application/pdf",
      pdfBuffer.toString("base64"),
      `prescription_${patientName}.pdf`
    );

    const facilityInfo = facilityName ? `\nFrom: ${facilityType} - ${facilityName}` : "";
    const caption = `Dear ${patientName},\n\nYour prescription from Dr. ${doctorName} is ready.${facilityInfo}\n\nPlease find the PDF attached.\n\nGenerated by MedAlerto 🏥`;

    await client.sendMessage(chatId, media, {
      caption: caption,
    });

    return true;
  } catch (error) {
    console.error("WhatsApp send error:", error);
    throw error;
  }
};

export default client;