import pkg from "whatsapp-web.js";
const { Client, LocalAuth, MessageMedia } = pkg;
import qrcode from "qrcode-terminal";

const client = new Client({
  authStrategy: new LocalAuth(),
  puppeteer: {
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  },
});

client.on("qr", (qr) => {
  console.log("📱 Scan this QR code with WhatsApp Business:");
  qrcode.generate(qr, { small: true });
});

client.on("ready", () => {
  console.log("✅ WhatsApp MedAlerto is ready!");
});

client.on("auth_failure", (msg) => {
  console.error("❌ WhatsApp auth failed:", msg);
});

client.on("disconnected", (reason) => {
  console.log("❌ WhatsApp disconnected:", reason);
  client.initialize();
});

client.initialize();

export const sendPrescriptionWhatsApp = async (phone, patientName, pdfBuffer) => {
  try {
    const formattedPhone = phone.replace(/\D/g, "");
    const whatsappPhone = formattedPhone.startsWith("0")
      ? "92" + formattedPhone.slice(1)
      : formattedPhone;
    const chatId = `${whatsappPhone}@c.us`;

    const media = new MessageMedia(
      "application/pdf",
      pdfBuffer.toString("base64"),
      `prescription_${patientName}.pdf`
    );

    await client.sendMessage(chatId, media, {
      caption: `Dear ${patientName}, please find your prescription attached.\n\nGenerated by MedAlerto 🏥`,
    });

    return true;
  } catch (error) {
    console.error("WhatsApp send error:", error);
    throw error;
  }
};

export default client;